{{- if .Values.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prospector-atlas.fullname" . }}-preview
  labels:
    {{- include "prospector-atlas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "prospector-atlas.selectorLabels" . | nindent 4 }}
{{- end }}
